; HEADER_BLOCK_START
; generated by OrcaSlicer 2.2.0 on 2025-01-15 at 01:06:50
; total layer number: 1
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 0.25
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 3404
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAJv0lEQVR4Ae3d7YpV1xnA8Z00UaPxPR
; qj0ZnRWgQtKqSFSjGWWlpLrRbFpi2SQfohMVAFA5Zi0BIMjaW1UFroJy/BS/ASvAQvwUuY5hk4gxmd
; mXP22S9r7fX7wf9bQmLUzd5P1rOsKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAsrf5Rz+Y3/rT0zcrgJTtnv/do0P/++dCtPfW9Sevb3xrWwWQkvX7
; 952Y+erOs9HDatTcw/vPN504drECSMH2X/387vIH1fLeuXLxobctoDfxVvX+nVtP13pYjYq/Nv6eCq
; BLMVQf90G1/BPRQB7oRHzW7fn02uM6D6sXi4H8Gzt3zFYAbXjre4fOxBvStA8rA3mgVTE0b+pBZSAP
; tGLSwXrdDOSBqdQdrE/ziRj/TG9bwNjigRFD8S4fVgbywMRiD7CvB9Xyt634d6kAXuXFPcBUiiMUPh
; GBJSvtAaZSDOQdfwDG2gNM5RMx/l29bUGBujqu0HQxkHf8AQrS9XGFNt627CPCwMXnVIqD9Wnethx/
; gAFKfbA+zduWgTwMSJt7gKlkHxEyl+tgvW72ESFTuQ/W62YfETLS1AV7uWcgD4lr+oK93LOPCIkqYb
; BetzjK4RMREjDU4wpNZx8RelbqYL1uBvLQg/gNV9JxhaYzkIeOpHLBXu7ZR4SWDWkPMJXibcsnIjTI
; YL3d7CNCQ3K5YG8I2UeEmkrbA0wl+4gwIccV+s1AHsZgDzCtHH+AFdgDTDP7iLCMPcD0s49I8RxXyK
; sYyMebcAWlMVjPM/uIFCV+occwN6ffpHo5A3kGzx7gsHL8gcGyBzjc7CMyGAbrZWQfkezZAyzvoWUf
; kezYAyw7+4hkw3EFRQbyJC0+AwzWtTzHH0iOwbpWy0CeZNgD1LgZyNMbg3XVyUCezhmsa5rsI9IJF+
; ypyQzkaU0MTV2wp6ZzQSCNM1hX27kgkKk5rqAui4G84w/UYg9QfWQgz0RiCOq4gvrOQJ41uWBPKWUf
; kRXZA1SquSCQJQbryiH7iDiuoOyyj1gge4DKOfuIBbEHqCHk+MPA2QPUEHP8YYDijxe3B6ihZh9xQA
; zWVUr2ETPmuIJKzD5ihgzWVXIG8pmIn6AYQub0i0tqKwP5hNkDlF7OPmKC7AFKq2cfMQEG69L42Ufs
; kQv2pHrZR+yQPUBp+uwjdsBxBam5DORbYg9Qai/HHxpkD1BqPwP5BtgDlLrNQL4Gg3WpvwzkJ2CwLv
; WffcQ12AOU0stA/hXsAUrp5oLAF9gDlPKo6AsC7QFK+VXkBYH2AKV8K2Yg77iCNJxiID/Y4w+OK0jD
; a3D7iPHaaLAuDbtBXBBosC6VU9b7iPYApTLLah/RYF1SFvuIBuuSRiV7/MEFe5JWKql9RBfsSVqrJP
; YRDdYlTVIv+4iOK0iqW6f7iAbrkqat9YG8C/YkNV0rA3kX7Elqq0b3Ee0BSuqiqfYR4zXNYF1Sl8Xb
; VhyVqib1zQPrxK6rVx4f/O/fs/oBS8q33R9/9OSN7dvqr/RsO/vhw7l/fZXVD1pSXs3+48uFLadPPa
; ya8Oa7u07su/2nZ962JDXdvts3nr+5e9eZqmk7zv/i0cF//y2r/xiS0uzgfx4svPPb3zyp2rThu3MX
; 99+7bXdQUu0O3L+zsOHwofmqC4sD+d9fNpCXNHG7/nB5usF6XTGQP/DlX7xtSVqzGKxvPvXDZgbrdR
; nIS1qrvbc+a2ewXlcM5B1/kPRi8Va148K5dgfrda3fv+/M/i8+94koaeH9Lz5fSOqt6lViIL94/MEn
; olRkcVwhBuuvb9o4W+Vi08nv3zSQl8oqPgE3HT+W558EHW9be29+aiAvFdB7Nz553stxhabZR5SGW7
; xVbT374aNqSOL4QwzkvW1JwymLwfo07CNK+dfJHmAq7CNK+Tbz9d2FjUeP5DlYr8s+opRfU1+wl7sY
; yM8+uJfVT5pUWknsAabCPqKUbq1dsJc7A3kpnWKwvvPS+TIG63UtDuTtI0q9tv+vf15YPzczX7E2+4
; hSf2W3B5gK+4hSd8Vg/e0PTt6tqM8+otR+yV2wlzv7iFLzDXIPMBWjfcScfkFIqTb4PcAUvLZu3TbH
; H6T6jfYADdY7FMcfDOSlySpyDzAV9hGl8St+DzAVBvLSysVgfcvpU/YAU2IfUXo5e4CJM5CX7AFmxQ
; WBKjl7gBmKgfw3/+vWQF5FFXuABusZ2/qTHz90/EFDzwV7AxID+b23PjOQ1yCzBzhQMZB3/EFDKd6q
; tp87+7hiuNbv33fGPqJyzx5gQZYuCHT8QZkVxxVcsFcoFwQqp+ITcNPxY/YAS+aCQOXQnuvXnjmuwB
; L7iEoxF+yxotEFgd62lEIG64zFQF59Nrpgr4Jx2UdUH8UFexsOH5qvYFIuCFSXuWCPRsRA3vEHtZU9
; QBrngkC1kT1AWmUgryaKwfqOC+cM1mmffURNU1yw562KTi3tI/pE1ATZA6RX9hE1TjFYf/uDk3cr6J
; t9RK2WwTpJso+oF7MHSPJG+4g5/cZS89kDJBuvrVu3zfGHMhvtARqskx37iGUVe4Abjx5xwR75so9Y
; RvYAGZQYyM8+uJfVb0KtnT1ABss+4rDad/uG4woMn4F83sVgfeel8/YAKcfiQN7xh+yKPcD1czPzFZ
; QmBvI7L//aQD6TYg/QYJ3i2UdMO3uAsIx9xDSzBwir2P7Lnz2yj9h/9gBhTC4I7Dd7gDChpQsCHX/o
; rDiu4II9mIKBfDfFJ+Cm48fsAcK04m1rz/VrTw3k2+ndP1596rgCNMwFgc0Wb1VbTp+yBwhtsY/YTP
; YAoUMG8vUaXbBXAd1yQeBkHbh/Z2HD4UPzFdAPFwSOlz1ASEgM5B1/eDkX7EGiDOS/nT1AyEAM5Es+
; /hBvVTsunDNYh1yUuo8YF+x5q4IMLe0jFvCJaA8QBmLo+4gu2IOBGeoFge/d+MRgHYZqKPuILtiDQs
; TxhxjI5/q25YI9KFBu+4j2AKFwuewjznx9d2Hj0SMu2IPSpb6PuPvjj+wBAt8WA/nZB/eSeVDZAwRW
; lco+ogv2gLH1NZCPwfrOS+cN1oHJLA7kO9xHjD3A9XMz8xVAHV3tI9oDBBrT1j6iPUCgFU3vI7pgD2
; jdtPuI9gCBTo32ESd9WNkDBHrxnc1vz457/GG0B2iwDvQqjj+sNpC3BwgkZXEf8eqVl/YR7QECyRoN
; 5GOwvuX0KXuAQNpiIG+wDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAwDP8HoVXDjK9UZAIAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 400x300 4472
; iVBORw0KGgoAAAANSUhEUgAAAZAAAAEsCAYAAADtt+XCAAAM4UlEQVR4Ae3d647cdR3H8Sng1La7dU
; tL2e1huwUCgWDEJjYlNDhBEU/VkhqIyIMFTIvYpiXUCKSkEgQEI9UYTXzUS+glcAm9hF5CL2H1N+2s
; 2+3udA7/w+/weiXvxKjxwaZ0M/P9+/l3OgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUauvB/c/seObpkx
; 0AGNWeV05eefQ/X62Ewr++b/u2uQ4AbCZ86jhw6b3rg18eg8K/F/6zDgCs960fPH9h/S+OtR2+8unN
; 8N/xaQSAvvALYf53b14b9stjbfvee+frB3Y/uNQBoFzbHn+0Fz5ZjPrLY+2nkdlnv7fcAaA8aw/lk7
; Z3+ddXfaUFUIhwDD/02aUb0/7yWHtg97gvQObudSifNAd2gEyFv9jD8buOXx4O7ACZCsfuun9xbPRp
; pANAusKRu8lfHus/jfhKCyAxVR/Kp/k04sAOkIhdP3/pctu/ONZnTwsgYpvtWMWSPS2ACNX1eG4dX2
; k5sANEYNwdq1jyuC9AiybdsYrp04gDO0DDqtixiiUHdoAGxH4onzQHdoAapXIonzR7WgAVa2rHKpYc
; 2AEq0PSOVUyfRrywCmBCbe5YxZIXVgGMIZYdq1jywiqAEcS4YxVDDuwAm8j18dyqCwd2j/sC3Jb747
; lVZ08LKF74OsahfPK8sAookkN5NdnTAoqS045VLNnTArLmUF5v9rSALDmUN5PHfYFspPrCp9SzpwUk
; LfUXPqWePS0gSQ7l8WRPC0iCx3PjzJ4WEDWH8rhzYAeiU9oLn1LPgR2IQqkvfEo9e1pAq+xYpZ89La
; BRDuV5ZU8LaIQXPuWbPS2gFnasysieFlApj+eWlQM7MDU7VmXncV9gInasFLKnBYzFjpXWZ08LGMrj
; uRpWOLCHT6YdgLUcyjVK9rSAVXasNEkO7FA4O1aaJo/7QqHsWKmqwqPevtKCAjiUq47Cnyl7WpAxO1
; aqs/CVVvgz5tMIZMSOlZosHNjtaUEGPJ6rNnJgh4SFrxEcytV2HveFxDiUK6a8sAoSYcdKseaFVRAp
; h3KlkBdWQWQcypVS9rQgAl74pJRzYIeWeOGTcsgLq6BhDuXKLS+sgpp5PFc5Fw7sHveFGtixUgk5sE
; OFwpHR47kqLQd2mJIXPqnk7GnBhOxYSbcKn0Z8pQUjcCiX7s6eFtyDx3Ol4dnTgnXsWEmjZ08LbrNj
; JY2fx30pmh0rafo87ktx7FhJ1WVPi2I4lEv1ZE+LbHk8V6o/e1pkx6Fcai4HdrIQ/gCHI19K//BJue
; TATrLsWEntZ0+L5NixkuLKnhbRcyiX4s2eFtHywicpjexpEQ07VlJ62dOidR7PldLNgZ1WhI+/DuVS
; Hnncl8aEj712rKS8cmCndnaspLxzYKdyDuVSOTmwUxmHcqm87GkxFS98kuTAztjCMS2lP+SS6ssLqx
; iZx3MlbZQXVrEpO1aS7pUXVnEXO1aSRs2BnT6P50qatHBg97hvoTyeK2na7GkVxo6VpKrzwqoCOJRL
; qit7WhmzYyWpiexpZcShXFLT2dPKgEO5pLbyuG+i7FhJiiV7WgnZ9vijPS98khRT9rQS4FAuKebsaU
; XI47mSUsmeVkQcyiWllgN7y8IPPhynUvpDI0lrc2BvQThGpfSHRJI2y55Wg+xYScoxe1o1ciiXlHv2
; tGrghU+SSsqeVgXsWEkqNXtaU/B4rqTSc2Afkx0rSbozj/uOwI6VJG2cA/sQdqwk6d7Z01rDoVySxs
; uBveNQLkmTVuyelh0rSaqmog7sdqwkqdqKeGGVHStJqq/wf4HI7istO1aS1Ezh79psHve1YyVJzRa+
; 0gp/9yb7acTjuZLUbuHAntzjvh7PlaQ4SmZPK3xcciiXpPiK+nFfh3JJirso97TsWElSOkXxwiqHck
; lKs1b3tBzKJSntGt/T8sInScqrRg7sXvgkSXlW656WQ7kk5V+lL6wK/0OLn3xwI6UfgCRp8voH9sUD
; vc607p+dWdr9q19ce+Sff0nqByBJGr9H/vXlyu5TJ76+b8f2pU5Vdj7/7JWDH110/5CkTDv48fsrO4
; 5850qnDv+70j8zf2b5xiP//mtSPxRJ0vDmf//bm9/Y+1CvU7e5H37/6tKXf0rqhyNJurulv32ysutn
; P/q606Tuvvne/j+ev+nTiCSl2f4PLqw08qljI+ErrV0/ffHq4b9/ltQPTZJKLnzqePCXP6n2UD6pHd
; /99gUHdkmKvwMfXVzZ/vSTlzsxWT2we9xXkqIrPJ778Jnlm619ZTWK8Ljvoc8/SuoHK0k5d+iLyyuz
; x49d7aQgfBrZf/GsA7sktdz+P5xbifpTx0a2dLtz4cAejjUp/bAlKYcGj+dGcSif1DcfO3wyHNh9Gp
; GkZgqH8m1PPHahk4PwlZY9LUmqt8GO1QO75tp502CdHNglqZ5q3bGKRf9x33fesqclSRXV2I5VLOZe
; esGeliRNUSs7VrEIB/YDH77rwC5JYxZ2rLYePrTcKVn4SuvBEz+2pyVJIxTVjlUs7GlJ0vCi3LGKhT
; 0tSbq78HhucYfySXlhlSTdKnxltbP3XBo7VrHo72l5YZWkgktyxyoW98/OLHlhlaTSciiv0Pannli2
; pyWphLLasYqFPS1JORcO5XtefTnPHatY2NOSlFvhhU8zR4/kvWMVi/BpZOHcaXtakpJv4fzbHs9tQ/
; +FVR73lZRgRe9YxcILqySllh2riDiwS0qhw//4vP94rkN5hMKB3Z6WpBgr4oVPqVvd0/KVlqRIsmOV
; GHtaktrOoTxh3X3zPXtaktrIjlUGwlda9rQkNZUdqwwNXljl04ikurJjlTEvrJJUR2HHau+bv7nh8d
; wC2NOSVFVhx2r2+DEvfCpJ/4VVF8/6SkvSxDmUF86elqRx83guq+xpSRq1cCi3Y8Ud7GlJGlY4lO8+
; dcKOFZuzpyVpfXasGJk9LUmD7FgxEXtaUrk5lDO1rUuLJ+1pSWXlhU9Uxp6WVEZ2rKjNYE8rpX8gJI
; 1WeDx3+9NPXu5AXexpSXkVHs91KKdR4XFfB3Yp7cJXVnasaEV/T8uBXUoyO1a0bku3O+fALqWTQznR
; saclxZ8XPhEte1pSnIVD+Z5XX7ZjRfy8sEqKp8VPL9mxIi3h08jCudP2tKQW83guSfPCKqn57FiRDQ
; d2qbnsWJGdwYHd475SPQ0ez3UoJ1v2tKTqs2NFMbywSqomO1YUywurpMkLX1nNvdi71oFSdffN9+xp
; SeNlxwpu88IqabTsWMEmBgd2n0aku7NjBfcQPo3sfeO16/a0pFuFQ/lDr79y3eO5MCJ7WtJXK4e+uL
; wyc/SIHSsYV/+FVRfP+kpLRbZw/m2P58K07GmppOxYQcXsaamEwqHcjhXUwAurlGvhUL771Ak7VlC3
; cGC3p6VcOvjx+174BE2yp6UcsmMFLbKnpRRzKIdI2NNSSoUXPvnUARGxp6XYs2MFkfPCKsWYFz5BIl
; YP7B73VcuFx3MfPrPsUA6pCY/7OrCrrcKO1ezxY1c7QJrsaamNvPAJMrGl251zYFcTOZRDpuxpqc68
; 8AkyZ09LVWfHCgrjhVWqIjtWUKj+477vvGVPSxNlxwrozL30gj0tjZwdK+AO4cB+4MN3Hdg1tLBj5Y
; VPwF0GB3aP+2p9g8dzHcqBoexpaW12rICx2NNSeDzXoRyYmBdWlVn4ympn7zk7VsB0+ntaXlhVTHas
; gErdPzuzZE8r7+xYAbXa/tQTy/a08suOFdCI8JXW3jdeu+7Ann7hUP7Q669c93gu0Ch7WmkXXvg0c/
; SIHSugHeHTyMK50/a0Emvh/NsezwXiEA7sHveNPztWQJS8sCru7FgBUfPCqvgKh3I7VkAywoHdnlb7
; eeETkKTVPS1fabWSHSsgefa0ms2hHMhKd998z55W/dmxArIUvtKyp1VPdqyAInhhVbV54RNQFC+smr
; 7weO7DZ5ZvejwXKJI9rckKO1azx4954RNQtv4Lqy6edWAfMYdygHXsaQ3P47kAQ9jT2jgvfAIYgT2t
; /xcO5btPnbBjBTCOcGBf/POHSf2FX2V2rACmUOqelh0rgIqUsqflUA5Qg61Liydz3tPywieAGuW4p2
; XHCqBBuexp2bECaEHKe1rh8VyHcoCWhcd9Uzqwh6+sdvaes2MFEIP+nlYCB3Y7VgAR2tLtzsV6YHco
; B0hAbHtadqwAEhLDnlY4lO959WU7VgApauuFVYufXlqZOXrEjhVAysKnkYVzpxvb0/J4LkBm6n5hlR
; 0rgIzVdWC3YwVQgMGBvYrHfQeP5zqUAxQkHNin2dPywieAgk3ywio7VgCsGvWFVeErq7kXe9c6ADDQ
; 3TffG7anZccKgE1t9MIqO1YAjGzwwio7VgCMLXwa8XguAAAAAAAAAAAAAAAAAAAAAAAAAAAAQMn+C5
; s9okcr3dO/AAAAAElFTkSuQmCC
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 32x32 544
; iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABXUlEQVR4Ae2Vz0oCURTGD/2hNMrUpq
; R/TgotomA2LdqE4KIIF0OQEBRIrapN4CqQhKIEEWflwtU8go/gI/gIPoKPoHzCwHVGueOdOwPC/OAb
; hpmB784537mXKCRkkYkXbqo7Rd1Yika2KUjWjg60w0q5l203hxDu8YyCIJa//rSMWZ0YfwO8I79AmX
; dLj+Y0c1b75ffuSjKhkkxQ3vR/pc8zZ6uxoZ3rJAOEzK2xXZ4Cag+aqIQCOitoorICyq0GPki9vXRk
; mrsOaOQ0m8NK/TJnq7F5dVmaMPcSNFFhpMctwQULCOLvWcHT0YJ5Zt1LC+A1M4TKc9H0yzz18dolN0
; QvznTZLXEEj8fqnqLJGElsRJ7OhoR+JxzQ5H3BIBlgKz3+/eq7NU7XvgfrGTVHMrHGlWeuPD2Y5CcY
; IbXx42hJplUfSjuCedjPDOzxy7EtlYIGJ1z8Nl+lkJBFZgQLr/anQ/l88AAAAABJRU5ErkJggg==
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.42mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Cube_id_0_copy_0 CENTER=175,175 POLYGON=[[137.5,137.5],[212.5,137.5],[212.5,212.5],[137.5,212.5],[137.5,137.5]]
M73 P0 R3
;TYPE:Custom
G28
G90
G1 X0 F9000
G1 Y20
G1 Z0.600 F600
G1 Y0 F9000
DZOS_SOAK_TIME TIME=0
START_PRINT TEMP=65
G90
G1 X0 F9000
G1 Y20
G1 Z0.600 F600
G1 Y0 F9000
M400
G91
M83
M140 S65 ;set bed temp
M104 S235 ;set extruder temp
M190 S65 ;wait for bed temp
M109 S235;wait for extruder temp
G1 E25 F300
G4 P1000
G1 E-0.200 Z5 F600
M73 P3 R3
M73 P3 R3
G1 X88.000 F9000
G1 Z-5.000 F600
G1 X87.000 E20.88 F1800
M73 P4 R3
M73 P4 R3
G1 X87.000 E13.92 F1800
M73 P5 R3
M73 P5 R3
G1 Y1 E0.16 F1800
M73 P7 R2
M73 P7 R2
G1 X-87.000 E13.92 F1800
G1 X-87.000 E20.88 F1800
M73 P8 R2
M73 P8 R2
G1 Y1 E0.24 F1800
M73 P10 R2
M73 P10 R2
G1 X87.000 E20.88 F1800
G1 X87.000 E13.92 F1800
M73 P11 R2
M73 P11 R2
G1 E-0.200 Z1 F600
M73 P13 R2
M400
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 S0
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
TIMELAPSE_TAKE_FRAME
G92 E0
M73 P13 R2
G1 E-.5 F1800
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=3000 ACCEL_TO_DECEL=1500
G1 Z.65 F36000
G1 X133.801 Y133.812
G1 Z.65
G1 Z.25
G1 E.5 F1800
;TYPE:Skirt
;WIDTH:0.5
G1 F3000
G1 X135.491 Y132.679 E.09249
G1 X137.5 Y132.277 E.09315
G1 X212.5 Y132.277 E3.40986
G1 X214.495 Y132.673 E.09249
M73 P14 R2
M73 P14 R2
G1 X216.188 Y133.801 E.09249
G1 X217.321 Y135.491 E.09249
G1 X217.723 Y137.5 E.09315
G1 X217.723 Y212.5 E3.40986
G1 X217.327 Y214.495 E.09249
M73 P15 R2
M73 P15 R2
G1 X216.199 Y216.188 E.09249
G1 X214.509 Y217.321 E.09249
G1 X212.5 Y217.723 E.09315
G1 X137.5 Y217.723 E3.40986
G1 X135.505 Y217.327 E.09249
M73 P16 R2
M73 P16 R2
G1 X133.812 Y216.199 E.09249
G1 X132.679 Y214.509 E.09249
G1 X132.277 Y212.5 E.09315
G1 X132.277 Y137.5 E3.40986
G1 X132.673 Y135.505 E.09249
G1 X133.779 Y133.845 E.09067
; printing object Cube id:0 copy 0
;WIPE_START
G1 X135.432 Y132.719 E-.5
;WIPE_END
EXCLUDE_OBJECT_START NAME=Cube_id_0_copy_0
G1 Z.65 F36000
G1 X212.15 Y212.15 Z.65
M73 P17 R2
M73 P17 R2
G1 Z.25
G1 E.5 F1800
;TYPE:Outer wall
G1 X137.85 Y212.15 E3.37803
G1 X137.85 Y137.85 E3.37803
M73 P18 R2
M73 P18 R2
G1 X212.15 Y137.85 E3.37803
M73 P19 R2
M73 P19 R2
G1 X212.15 Y212.13 E3.37712
M73 P21 R2
M73 P21 R2
G1 X211.704 Y211.704 F36000
M73 P22 R2
;TYPE:Inner wall
M73 P22 R2
G1 F1800
G1 X138.296 Y211.704 E3.33745
G1 X138.296 Y138.296 E3.33745
M73 P23 R2
M73 P23 R2
G1 X211.704 Y138.296 E3.33745
M73 P24 R2
M73 P24 R2
G1 X211.704 Y211.684 E3.33654
M73 P26 R2
;WIPE_START
M73 P26 R2
G1 X209.704 Y211.684 E-.5
M73 P27 R2
;WIPE_END
M73 P27 R2
G1 Z.65 F36000
G1 X211.57 Y139.336 Z.65
G1 Z.25
G1 E.5 F1800
;TYPE:Bottom surface
;WIDTH:0.501693
G1 F5400
G1 X210.865 Y138.631 E.0455
G1 X210.231 Y138.631 E.02892
G1 X211.369 Y139.769 E.07343
G1 X211.369 Y140.403 E.02892
G1 X209.597 Y138.631 E.11433
G1 X208.964 Y138.631 E.02892
G1 X211.369 Y141.036 E.15522
G1 X211.369 Y141.67 E.02892
G1 X208.33 Y138.631 E.19612
G1 X207.697 Y138.631 E.02892
G1 X211.369 Y142.303 E.23701
G1 X211.369 Y142.937 E.02892
G1 X207.063 Y138.631 E.27791
G1 X206.429 Y138.631 E.02892
M73 P28 R2
M73 P28 R2
G1 X211.369 Y143.571 E.3188
G1 X211.369 Y144.204 E.02892
G1 X205.796 Y138.631 E.3597
G1 X205.162 Y138.631 E.02892
G1 X211.369 Y144.838 E.40059
G1 X211.369 Y145.472 E.02892
G1 X204.528 Y138.631 E.44149
G1 X203.895 Y138.631 E.02892
G1 X211.369 Y146.105 E.48238
G1 X211.369 Y146.739 E.02892
G1 X203.261 Y138.631 E.52328
G1 X202.628 Y138.631 E.02892
G1 X211.369 Y147.372 E.56417
G1 X211.369 Y148.006 E.02892
G1 X201.994 Y138.631 E.60507
G1 X201.36 Y138.631 E.02892
G1 X211.369 Y148.64 E.64596
G1 X211.369 Y149.273 E.02892
G1 X200.727 Y138.631 E.68686
G1 X200.093 Y138.631 E.02892
G1 X211.369 Y149.907 E.72775
G1 X211.369 Y150.541 E.02892
G1 X199.459 Y138.631 E.76865
G1 X198.826 Y138.631 E.02892
M73 P29 R2
M73 P29 R2
G1 X211.369 Y151.174 E.80954
G1 X211.369 Y151.808 E.02892
G1 X198.192 Y138.631 E.85044
G1 X197.559 Y138.631 E.02892
G1 X211.369 Y152.441 E.89133
G1 X211.369 Y153.075 E.02892
G1 X196.925 Y138.631 E.93223
G1 X196.291 Y138.631 E.02892
G1 X211.369 Y153.709 E.97312
G1 X211.369 Y154.342 E.02892
G1 X195.658 Y138.631 E1.01402
G1 X195.024 Y138.631 E.02892
G1 X211.369 Y154.976 E1.05491
G1 X211.369 Y155.61 E.02892
G1 X194.39 Y138.631 E1.09581
M73 P30 R2
M73 P30 R2
G1 X193.757 Y138.631 E.02892
G1 X211.369 Y156.243 E1.1367
G1 X211.369 Y156.877 E.02892
G1 X193.123 Y138.631 E1.1776
G1 X192.49 Y138.631 E.02892
G1 X211.369 Y157.51 E1.21849
G1 X211.369 Y158.144 E.02892
G1 X191.856 Y138.631 E1.25939
G1 X191.222 Y138.631 E.02892
G1 X211.369 Y158.778 E1.30028
G1 X211.369 Y159.411 E.02892
M73 P31 R2
M73 P31 R2
G1 X190.589 Y138.631 E1.34118
G1 X189.955 Y138.631 E.02892
G1 X211.369 Y160.045 E1.38207
G1 X211.369 Y160.679 E.02892
G1 X189.321 Y138.631 E1.42297
G1 X188.688 Y138.631 E.02892
G1 X211.369 Y161.312 E1.46386
G1 X211.369 Y161.946 E.02892
G1 X188.054 Y138.631 E1.50476
G1 X187.42 Y138.631 E.02892
G1 X211.369 Y162.58 E1.54565
M73 P32 R2
M73 P32 R2
G1 X211.369 Y163.213 E.02892
G1 X186.787 Y138.631 E1.58655
G1 X186.153 Y138.631 E.02892
G1 X211.369 Y163.847 E1.62744
G1 X211.369 Y164.48 E.02892
G1 X185.52 Y138.631 E1.66834
G1 X184.886 Y138.631 E.02892
G1 X211.369 Y165.114 E1.70923
G1 X211.369 Y165.748 E.02892
M73 P33 R2
M73 P33 R2
G1 X184.252 Y138.631 E1.75013
G1 X183.619 Y138.631 E.02892
G1 X211.369 Y166.381 E1.79102
G1 X211.369 Y167.015 E.02892
G1 X182.985 Y138.631 E1.83192
G1 X182.351 Y138.631 E.02892
G1 X211.369 Y167.649 E1.87281
G1 X211.369 Y168.282 E.02892
M73 P34 R2
M73 P34 R2
G1 X181.718 Y138.631 E1.91371
G1 X181.084 Y138.631 E.02892
G1 X211.369 Y168.916 E1.9546
G1 X211.369 Y169.549 E.02892
G1 X180.451 Y138.631 E1.9955
G1 X179.817 Y138.631 E.02892
G1 X211.369 Y170.183 E2.03639
G1 X211.369 Y170.817 E.02892
M73 P35 R2
M73 P35 R2
G1 X179.183 Y138.631 E2.07729
G1 X178.55 Y138.631 E.02892
G1 X211.369 Y171.45 E2.11818
G1 X211.369 Y172.084 E.02892
G1 X177.916 Y138.631 E2.15908
G1 X177.282 Y138.631 E.02892
M73 P36 R2
M73 P36 R2
G1 X211.369 Y172.718 E2.19997
G1 X211.369 Y173.351 E.02892
G1 X176.649 Y138.631 E2.24087
G1 X176.015 Y138.631 E.02892
G1 X211.369 Y173.985 E2.28176
G1 X211.369 Y174.618 E.02892
G1 X175.382 Y138.631 E2.32266
G1 X174.748 Y138.631 E.02892
M73 P37 R2
M73 P37 R2
G1 X211.369 Y175.252 E2.36355
G1 X211.369 Y175.886 E.02892
G1 X174.114 Y138.631 E2.40445
G1 X173.481 Y138.631 E.02892
M73 P37 R1
M73 P37 R1
G1 X211.369 Y176.519 E2.44534
G1 X211.369 Y177.153 E.02892
M73 P38 R1
M73 P38 R1
G1 X172.847 Y138.631 E2.48624
G1 X172.213 Y138.631 E.02892
G1 X211.369 Y177.787 E2.52713
G1 X211.369 Y178.42 E.02892
G1 X171.58 Y138.631 E2.56803
G1 X170.946 Y138.631 E.02892
M73 P39 R1
M73 P39 R1
G1 X211.369 Y179.054 E2.60892
G1 X211.369 Y179.687 E.02892
G1 X170.313 Y138.631 E2.64981
G1 X169.679 Y138.631 E.02892
G1 X211.369 Y180.321 E2.69071
G1 X211.369 Y180.955 E.02892
M73 P40 R1
M73 P40 R1
G1 X169.045 Y138.631 E2.7316
G1 X168.412 Y138.631 E.02892
G1 X211.369 Y181.588 E2.7725
G1 X211.369 Y182.222 E.02892
M73 P41 R1
M73 P41 R1
G1 X167.778 Y138.631 E2.81339
G1 X167.144 Y138.631 E.02892
G1 X211.369 Y182.856 E2.85429
G1 X211.369 Y183.489 E.02892
G1 X166.511 Y138.631 E2.89518
G1 X165.877 Y138.631 E.02892
M73 P42 R1
M73 P42 R1
G1 X211.369 Y184.123 E2.93608
G1 X211.369 Y184.757 E.02892
G1 X165.243 Y138.631 E2.97697
G1 X164.61 Y138.631 E.02892
G1 X211.369 Y185.39 E3.01787
G1 X211.369 Y186.024 E.02892
M73 P43 R1
M73 P43 R1
G1 X163.976 Y138.631 E3.05876
G1 X163.343 Y138.631 E.02892
G1 X211.369 Y186.657 E3.09966
G1 X211.369 Y187.291 E.02892
M73 P44 R1
M73 P44 R1
G1 X162.709 Y138.631 E3.14055
G1 X162.075 Y138.631 E.02892
G1 X211.369 Y187.925 E3.18145
G1 X211.369 Y188.558 E.02892
G1 X161.442 Y138.631 E3.22234
G1 X160.808 Y138.631 E.02892
M73 P45 R1
M73 P45 R1
G1 X211.369 Y189.192 E3.26324
G1 X211.369 Y189.826 E.02892
G1 X160.174 Y138.631 E3.30413
G1 X159.541 Y138.631 E.02892
M73 P46 R1
M73 P46 R1
G1 X211.369 Y190.459 E3.34503
G1 X211.369 Y191.093 E.02892
G1 X158.907 Y138.631 E3.38592
G1 X158.274 Y138.631 E.02892
M73 P47 R1
M73 P47 R1
G1 X211.369 Y191.726 E3.42682
G1 X211.369 Y192.36 E.02892
G1 X157.64 Y138.631 E3.46771
G1 X157.006 Y138.631 E.02892
M73 P48 R1
M73 P48 R1
G1 X211.369 Y192.994 E3.50861
G1 X211.369 Y193.627 E.02892
G1 X156.373 Y138.631 E3.5495
G1 X155.739 Y138.631 E.02892
G1 X211.369 Y194.261 E3.5904
M73 P49 R1
M73 P49 R1
G1 X211.369 Y194.895 E.02892
G1 X155.105 Y138.631 E3.63129
G1 X154.472 Y138.631 E.02892
G1 X211.369 Y195.528 E3.67219
G1 X211.369 Y196.162 E.02892
M73 P50 R1
M73 P50 R1
G1 X153.838 Y138.631 E3.71308
G1 X153.205 Y138.631 E.02892
G1 X211.369 Y196.795 E3.75398
G1 X211.369 Y197.429 E.02892
M73 P51 R1
M73 P51 R1
G1 X152.571 Y138.631 E3.79487
G1 X151.937 Y138.631 E.02892
G1 X211.369 Y198.063 E3.83577
G1 X211.369 Y198.696 E.02892
M73 P52 R1
M73 P52 R1
G1 X151.304 Y138.631 E3.87666
G1 X150.67 Y138.631 E.02892
G1 X211.369 Y199.33 E3.91756
G1 X211.369 Y199.964 E.02892
M73 P53 R1
M73 P53 R1
G1 X150.036 Y138.631 E3.95845
G1 X149.403 Y138.631 E.02892
G1 X211.369 Y200.597 E3.99935
G1 X211.369 Y201.231 E.02892
M73 P54 R1
M73 P54 R1
G1 X148.769 Y138.631 E4.04024
G1 X148.136 Y138.631 E.02892
G1 X211.369 Y201.864 E4.08114
M73 P55 R1
M73 P55 R1
G1 X211.369 Y202.498 E.02892
G1 X147.502 Y138.631 E4.12203
G1 X146.868 Y138.631 E.02892
M73 P56 R1
M73 P56 R1
G1 X211.369 Y203.132 E4.16293
G1 X211.369 Y203.765 E.02892
G1 X146.235 Y138.631 E4.20382
G1 X145.601 Y138.631 E.02892
M73 P57 R1
M73 P57 R1
G1 X211.369 Y204.399 E4.24472
G1 X211.369 Y205.033 E.02892
G1 X144.967 Y138.631 E4.28561
G1 X144.334 Y138.631 E.02892
M73 P58 R1
M73 P58 R1
G1 X211.369 Y205.666 E4.32651
G1 X211.369 Y206.3 E.02892
G1 X143.7 Y138.631 E4.3674
G1 X143.066 Y138.631 E.02892
M73 P59 R1
M73 P59 R1
G1 X211.369 Y206.934 E4.4083
G1 X211.369 Y207.567 E.02892
G1 X142.433 Y138.631 E4.44919
M73 P60 R1
M73 P60 R1
G1 X141.799 Y138.631 E.02892
G1 X211.369 Y208.201 E4.49009
G1 X211.369 Y208.834 E.02892
M73 P61 R1
M73 P61 R1
G1 X141.166 Y138.631 E4.53098
G1 X140.532 Y138.631 E.02892
G1 X211.369 Y209.468 E4.57188
G1 X211.369 Y210.102 E.02892
M73 P62 R1
M73 P62 R1
G1 X139.898 Y138.631 E4.61277
G1 X139.265 Y138.631 E.02892
G1 X211.369 Y210.735 E4.65367
G1 X211.369 Y211.369 E.02892
M73 P63 R1
M73 P63 R1
G1 X138.631 Y138.631 E4.69456
G1 X138.631 Y139.265 E.02892
M73 P64 R1
M73 P64 R1
G1 X210.735 Y211.369 E4.65366
G1 X210.102 Y211.369 E.02892
G1 X138.631 Y139.898 E4.61277
G1 X138.631 Y140.532 E.02892
M73 P65 R1
M73 P65 R1
G1 X209.468 Y211.369 E4.57187
G1 X208.834 Y211.369 E.02892
G1 X138.631 Y141.166 E4.53098
G1 X138.631 Y141.799 E.02892
M73 P66 R1
M73 P66 R1
G1 X208.201 Y211.369 E4.49008
G1 X207.567 Y211.369 E.02892
M73 P67 R1
M73 P67 R1
G1 X138.631 Y142.433 E4.44919
G1 X138.631 Y143.067 E.02892
G1 X206.933 Y211.369 E4.40829
G1 X206.3 Y211.369 E.02892
M73 P68 R1
M73 P68 R1
G1 X138.631 Y143.7 E4.3674
G1 X138.631 Y144.334 E.02892
G1 X205.666 Y211.369 E4.3265
G1 X205.033 Y211.369 E.02892
M73 P69 R0
M73 P69 R0
G1 X138.631 Y144.967 E4.28561
G1 X138.631 Y145.601 E.02892
M73 P70 R0
M73 P70 R0
G1 X204.399 Y211.369 E4.24471
G1 X203.765 Y211.369 E.02892
G1 X138.631 Y146.235 E4.20382
G1 X138.631 Y146.868 E.02892
M73 P71 R0
M73 P71 R0
G1 X203.132 Y211.369 E4.16292
G1 X202.498 Y211.369 E.02892
G1 X138.631 Y147.502 E4.12203
G1 X138.631 Y148.136 E.02892
M73 P72 R0
M73 P72 R0
G1 X201.864 Y211.369 E4.08113
G1 X201.231 Y211.369 E.02892
G1 X138.631 Y148.769 E4.04024
G1 X138.631 Y149.403 E.02892
M73 P73 R0
M73 P73 R0
G1 X200.597 Y211.369 E3.99934
G1 X199.964 Y211.369 E.02892
G1 X138.631 Y150.036 E3.95845
G1 X138.631 Y150.67 E.02892
M73 P74 R0
M73 P74 R0
G1 X199.33 Y211.369 E3.91755
G1 X198.696 Y211.369 E.02892
G1 X138.631 Y151.304 E3.87666
G1 X138.631 Y151.937 E.02892
M73 P75 R0
M73 P75 R0
G1 X198.063 Y211.369 E3.83576
G1 X197.429 Y211.369 E.02892
G1 X138.631 Y152.571 E3.79487
G1 X138.631 Y153.205 E.02892
M73 P76 R0
M73 P76 R0
G1 X196.795 Y211.369 E3.75397
G1 X196.162 Y211.369 E.02892
G1 X138.631 Y153.838 E3.71308
G1 X138.631 Y154.472 E.02892
M73 P77 R0
M73 P77 R0
G1 X195.528 Y211.369 E3.67218
G1 X194.895 Y211.369 E.02892
G1 X138.631 Y155.105 E3.63129
G1 X138.631 Y155.739 E.02892
M73 P78 R0
M73 P78 R0
G1 X194.261 Y211.369 E3.5904
G1 X193.627 Y211.369 E.02892
G1 X138.631 Y156.373 E3.5495
G1 X138.631 Y157.006 E.02892
M73 P79 R0
M73 P79 R0
G1 X192.994 Y211.369 E3.50861
G1 X192.36 Y211.369 E.02892
G1 X138.631 Y157.64 E3.46771
G1 X138.631 Y158.274 E.02892
M73 P80 R0
M73 P80 R0
G1 X191.726 Y211.369 E3.42682
G1 X191.093 Y211.369 E.02892
G1 X138.631 Y158.907 E3.38592
G1 X138.631 Y159.541 E.02892
M73 P81 R0
M73 P81 R0
G1 X190.459 Y211.369 E3.34503
G1 X189.825 Y211.369 E.02892
G1 X138.631 Y160.175 E3.30413
G1 X138.631 Y160.808 E.02892
G1 X189.192 Y211.369 E3.26324
G1 X188.558 Y211.369 E.02892
M73 P82 R0
M73 P82 R0
G1 X138.631 Y161.442 E3.22234
G1 X138.631 Y162.075 E.02892
G1 X187.925 Y211.369 E3.18145
G1 X187.291 Y211.369 E.02892
M73 P83 R0
M73 P83 R0
G1 X138.631 Y162.709 E3.14055
G1 X138.631 Y163.343 E.02892
G1 X186.657 Y211.369 E3.09966
G1 X186.024 Y211.369 E.02892
G1 X138.631 Y163.976 E3.05876
G1 X138.631 Y164.61 E.02892
M73 P84 R0
M73 P84 R0
G1 X185.39 Y211.369 E3.01787
G1 X184.756 Y211.369 E.02892
G1 X138.631 Y165.244 E2.97697
G1 X138.631 Y165.877 E.02892
M73 P85 R0
M73 P85 R0
G1 X184.123 Y211.369 E2.93608
G1 X183.489 Y211.369 E.02892
G1 X138.631 Y166.511 E2.89518
G1 X138.631 Y167.144 E.02892
G1 X182.856 Y211.369 E2.85429
G1 X182.222 Y211.369 E.02892
M73 P86 R0
M73 P86 R0
G1 X138.631 Y167.778 E2.81339
G1 X138.631 Y168.412 E.02892
G1 X181.588 Y211.369 E2.7725
G1 X180.955 Y211.369 E.02892
M73 P87 R0
M73 P87 R0
G1 X138.631 Y169.045 E2.7316
G1 X138.631 Y169.679 E.02892
G1 X180.321 Y211.369 E2.69071
G1 X179.687 Y211.369 E.02892
G1 X138.631 Y170.313 E2.64981
G1 X138.631 Y170.946 E.02892
M73 P88 R0
M73 P88 R0
G1 X179.054 Y211.369 E2.60892
G1 X178.42 Y211.369 E.02892
G1 X138.631 Y171.58 E2.56802
G1 X138.631 Y172.213 E.02892
G1 X177.787 Y211.369 E2.52713
G1 X177.153 Y211.369 E.02892
M73 P89 R0
M73 P89 R0
G1 X138.631 Y172.847 E2.48623
G1 X138.631 Y173.481 E.02892
G1 X176.519 Y211.369 E2.44534
G1 X175.886 Y211.369 E.02892
G1 X138.631 Y174.114 E2.40444
G1 X138.631 Y174.748 E.02892
M73 P90 R0
M73 P90 R0
G1 X175.252 Y211.369 E2.36355
G1 X174.618 Y211.369 E.02892
G1 X138.631 Y175.382 E2.32265
G1 X138.631 Y176.015 E.02892
G1 X173.985 Y211.369 E2.28176
G1 X173.351 Y211.369 E.02892
M73 P91 R0
M73 P91 R0
G1 X138.631 Y176.649 E2.24086
G1 X138.631 Y177.282 E.02892
G1 X172.718 Y211.369 E2.19997
G1 X172.084 Y211.369 E.02892
G1 X138.631 Y177.916 E2.15907
G1 X138.631 Y178.55 E.02892
G1 X171.45 Y211.369 E2.11818
G1 X170.817 Y211.369 E.02892
M73 P92 R0
M73 P92 R0
G1 X138.631 Y179.183 E2.07728
G1 X138.631 Y179.817 E.02892
G1 X170.183 Y211.369 E2.03639
G1 X169.549 Y211.369 E.02892
G1 X138.631 Y180.451 E1.99549
G1 X138.631 Y181.084 E.02892
M73 P93 R0
M73 P93 R0
G1 X168.916 Y211.369 E1.9546
G1 X168.282 Y211.369 E.02892
G1 X138.631 Y181.718 E1.9137
G1 X138.631 Y182.352 E.02892
G1 X167.649 Y211.369 E1.87281
G1 X167.015 Y211.369 E.02892
G1 X138.631 Y182.985 E1.83191
G1 X138.631 Y183.619 E.02892
M73 P94 R0
M73 P94 R0
G1 X166.381 Y211.369 E1.79102
G1 X165.748 Y211.369 E.02892
G1 X138.631 Y184.252 E1.75012
G1 X138.631 Y184.886 E.02892
G1 X165.114 Y211.369 E1.70923
G1 X164.48 Y211.369 E.02892
G1 X138.631 Y185.52 E1.66833
G1 X138.631 Y186.153 E.02892
M73 P95 R0
M73 P95 R0
G1 X163.847 Y211.369 E1.62744
G1 X163.213 Y211.369 E.02892
G1 X138.631 Y186.787 E1.58654
G1 X138.631 Y187.421 E.02892
G1 X162.579 Y211.369 E1.54565
G1 X161.946 Y211.369 E.02892
G1 X138.631 Y188.054 E1.50475
G1 X138.631 Y188.688 E.02892
G1 X161.312 Y211.369 E1.46386
G1 X160.679 Y211.369 E.02892
M73 P96 R0
M73 P96 R0
G1 X138.631 Y189.321 E1.42296
G1 X138.631 Y189.955 E.02892
G1 X160.045 Y211.369 E1.38207
G1 X159.411 Y211.369 E.02892
G1 X138.631 Y190.589 E1.34117
G1 X138.631 Y191.222 E.02892
G1 X158.778 Y211.369 E1.30028
G1 X158.144 Y211.369 E.02892
G1 X138.631 Y191.856 E1.25938
G1 X138.631 Y192.49 E.02892
M73 P97 R0
M73 P97 R0
G1 X157.51 Y211.369 E1.21849
G1 X156.877 Y211.369 E.02892
G1 X138.631 Y193.123 E1.17759
G1 X138.631 Y193.757 E.02892
G1 X156.243 Y211.369 E1.1367
G1 X155.61 Y211.369 E.02892
G1 X138.631 Y194.39 E1.0958
G1 X138.631 Y195.024 E.02892
G1 X154.976 Y211.369 E1.05491
G1 X154.342 Y211.369 E.02892
G1 X138.631 Y195.658 E1.01401
G1 X138.631 Y196.291 E.02892
M73 P98 R0
M73 P98 R0
G1 X153.709 Y211.369 E.97312
G1 X153.075 Y211.369 E.02892
G1 X138.631 Y196.925 E.93222
G1 X138.631 Y197.559 E.02892
G1 X152.441 Y211.369 E.89133
G1 X151.808 Y211.369 E.02892
G1 X138.631 Y198.192 E.85043
G1 X138.631 Y198.826 E.02892
G1 X151.174 Y211.369 E.80954
G1 X150.541 Y211.369 E.02892
G1 X138.631 Y199.459 E.76864
G1 X138.631 Y200.093 E.02892
G1 X149.907 Y211.369 E.72775
G1 X149.273 Y211.369 E.02892
G1 X138.631 Y200.727 E.68685
G1 X138.631 Y201.36 E.02892
M73 P99 R0
M73 P99 R0
G1 X148.64 Y211.369 E.64596
G1 X148.006 Y211.369 E.02892
G1 X138.631 Y201.994 E.60506
G1 X138.631 Y202.628 E.02892
G1 X147.372 Y211.369 E.56417
G1 X146.739 Y211.369 E.02892
G1 X138.631 Y203.261 E.52327
G1 X138.631 Y203.895 E.02892
G1 X146.105 Y211.369 E.48238
G1 X145.472 Y211.369 E.02892
G1 X138.631 Y204.528 E.44149
G1 X138.631 Y205.162 E.02892
G1 X144.838 Y211.369 E.40059
G1 X144.204 Y211.369 E.02892
G1 X138.631 Y205.796 E.3597
G1 X138.631 Y206.429 E.02892
G1 X143.571 Y211.369 E.3188
G1 X142.937 Y211.369 E.02892
G1 X138.631 Y207.063 E.27791
G1 X138.631 Y207.697 E.02892
G1 X142.303 Y211.369 E.23701
G1 X141.67 Y211.369 E.02892
G1 X138.631 Y208.33 E.19612
G1 X138.631 Y208.964 E.02892
G1 X141.036 Y211.369 E.15522
G1 X140.402 Y211.369 E.02892
G1 X138.631 Y209.598 E.11433
G1 X138.631 Y210.231 E.02892
G1 X139.769 Y211.369 E.07343
G1 X139.135 Y211.369 E.02892
G1 X138.43 Y210.664 E.0455
; stop printing object Cube id:0 copy 0
;WIPE_START
G1 F5400
G1 X139.135 Y211.369 E-.24924
G1 X139.769 Y211.369 E-.15841
G1 X139.508 Y211.108 E-.09235
;WIPE_END
EXCLUDE_OBJECT_END NAME=Cube_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 692.32
; filament used [cm3] = 1.67
; filament used [g] = 2.06
; filament cost = 0.04
; total filament used [g] = 2.06
; total filament cost = 0.04
; total layers count = 1
; estimated printing time (normal mode) = 3m 12s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; adaptive_pressure_advance = 0
; adaptive_pressure_advance_bridges = 0
; adaptive_pressure_advance_model = "0,0,0\n0,0,0"
; adaptive_pressure_advance_overhangs = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = TIMELAPSE_TAKE_FRAME\nG92 E0
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 3
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = monotonic
; bridge_acceleration = 100%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 1
; bridge_no_support = 0
; bridge_speed = 50
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0
; brim_type = auto_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = 
; close_fan_the_first_x_layers = 1
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 60
; cool_plate_temp_initial_layer = 55
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 20000
; default_filament_colour = ""
; default_filament_profile = "Sovol SV08 PLA"
; default_jerk = 0
; default_print_profile = 0.20mm Standard @Sovol SV08
; deretraction_speed = 30
; detect_narrow_internal_solid_infill = 1
; detect_overhang_wall = 1
; detect_thin_wall = 1
; different_settings_to_system = brim_type;skirt_distance;;
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; dont_slow_down_outer_wall = 0
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0.1
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_long_retraction_when_cut = 0
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 60
; eng_plate_temp_initial_layer = 55
; ensure_vertical_shell_thickness = ensure_all
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 140
; extruder_clearance_height_to_rod = 36
; extruder_clearance_radius = 65
; extruder_colour = #26A69A
; extruder_offset = 0x0
; fan_cooling_layer_time = 50
; fan_kickstart = 0
; fan_max_speed = 70
; fan_min_speed = 50
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #26A69A
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 20
; filament_density = 1.24
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.98
; filament_ids = GFL99
; filament_is_support = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 21
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Sovol SV08 PLA"
; filament_shrink = 100%
; filament_shrinkage_compensation_z = 100%
; filament_soluble = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filename_format = {input_filename_base}_{filament_type[0]}_{layer_height}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = nowhere
; gap_infill_speed = 200
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 65
; hot_plate_temp_initial_layer = 65
; idle_temperature = 0
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_combination_max_layer_height = 100%
; infill_direction = 45
; infill_jerk = 9
; infill_wall_overlap = 30%
; initial_layer_acceleration = 3000
; initial_layer_infill_speed = 90
; initial_layer_jerk = 9
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.25
; initial_layer_speed = 30
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 12000
; inner_wall_jerk = 9
; inner_wall_line_width = 0.42
; inner_wall_speed = 300
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; internal_bridge_flow = 1
; internal_bridge_speed = 50
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.45
; internal_solid_infill_pattern = monotonic
; internal_solid_infill_speed = 200
; ironing_angle = -1
; ironing_flow = 15%
; ironing_pattern = zig-zag
; ironing_spacing = 0.25
; ironing_speed = 15
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.4
; long_retractions_when_cut = 0
; machine_end_gcode = END_PRINT\n
; machine_load_filament_time = 0
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 5000
; machine_max_acceleration_travel = 40000
; machine_max_acceleration_x = 40000
; machine_max_acceleration_y = 40000
; machine_max_acceleration_z = 500
; machine_max_jerk_e = 5
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 0.5
; machine_max_speed_e = 50
; machine_max_speed_x = 700
; machine_max_speed_y = 700
; machine_max_speed_z = 20
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; machine_pause_gcode = 
; machine_start_gcode = G28\nG90\nG1 X0 F9000\nG1 Y20\nG1 Z0.600 F600\nG1 Y0 F9000\nSTART_PRINT\nG90\nG1 X0 F9000\nG1 Y20\nG1 Z0.600 F600\nG1 Y0 F9000\nM400\nG91\nM83\nM140 S[bed_temperature_initial_layer_single] ;set bed temp\nM104 S[nozzle_temperature_initial_layer] ;set extruder temp\nM190 S[bed_temperature_initial_layer_single] ;wait for bed temp\nM109 S[nozzle_temperature_initial_layer];wait for extruder temp\nG1 E25 F300\nG4 P1000\nG1 E-0.200 Z5 F600\nG1 X88.000 F9000\nG1 Z-5.000 F600\nG1 X87.000 E20.88 F1800\nG1 X87.000 E13.92 F1800\nG1 Y1 E0.16 F1800\nG1 X-87.000 E13.92 F1800\nG1 X-87.000 E20.88 F1800\nG1 Y1 E0.24 F1800\nG1 X87.000 E20.88 F1800\nG1 X87.000 E13.92 F1800\nG1 E-0.200 Z1 F600\nM400\n
; machine_tool_change_time = 0
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 0
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_skirt_length = 0
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_height = 2.5
; nozzle_hrc = 0
; nozzle_temperature = 220
; nozzle_temperature_initial_layer = 235
; nozzle_temperature_range_high = 250
; nozzle_temperature_range_low = 190
; nozzle_type = undefine
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; other_layers_print_sequence = 0
; other_layers_print_sequence_nums = 0
; outer_wall_acceleration = 8000
; outer_wall_jerk = 9
; outer_wall_line_width = 0.4
; outer_wall_speed = 200
; overhang_1_4_speed = 0
; overhang_2_4_speed = 50
; overhang_3_4_speed = 30
; overhang_4_4_speed = 10
; overhang_fan_speed = 100
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; pellet_flow_coefficient = 0.4157
; pellet_modded_printer = 0
; post_process = 
; precise_outer_wall = 0
; precise_z_height = 0
; preferred_orientation = 0
; preheat_steps = 1
; preheat_time = 30
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Sovol SV08 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm Standard @Sovol SV08 0.4 nozzle
; printable_area = 0x0,350x0,350x350,0x350
; printable_height = 345
; printer_model = Sovol SV08
; printer_notes = 
; printer_settings_id = Sovol SV08 0.4 nozzle
; printer_structure = undefine
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 1
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 0%
; retract_length_toolchange = 2
; retract_lift_above = 0
; retract_lift_below = 343
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_distances_when_cut = 18
; retraction_length = 0.5
; retraction_minimum_travel = 1
; retraction_speed = 30
; role_based_wipe_speed = 1
; rotate_solid_infill_direction = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 5%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 0
; skirt_distance = 5
; skirt_height = 1
; skirt_loops = 1
; skirt_speed = 50
; skirt_start_angle = -135
; skirt_type = combined
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 5
; slow_down_layers = 3
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 1
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_direction = 45
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 10%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.45
; sparse_infill_pattern = crosshatch
; sparse_infill_speed = 300
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 1
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 1
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = -1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.45
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 80
; support_style = snug
; support_threshold_angle = 20
; support_top_z_distance = 0.2
; support_type = normal(auto)
; temperature_vitrification = 60
; template_custom_gcode = 
; textured_cool_plate_temp = 40
; textured_cool_plate_temp_initial_layer = 40
; textured_plate_temp = 60
; textured_plate_temp_initial_layer = 55
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 300x300/PNG, 400x300/PNG, 32x32/PNG
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = 
; timelapse_type = 0
; top_bottom_infill_wall_overlap = 25%
; top_shell_layers = 4
; top_shell_thickness = 1
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 12000
; top_surface_jerk = 9
; top_surface_line_width = 0.42
; top_surface_pattern = monotonicline
; top_surface_speed = 200
; travel_acceleration = 20000
; travel_jerk = 12
; travel_slope = 3
; travel_speed = 600
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = outer wall/inner wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 2
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_filament = 0
; wipe_tower_max_purge_speed = 90
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 165.000
; wipe_tower_x = 165
; wipe_tower_y = 250.000
; wipe_tower_y = 250
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.4
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 65
; bed_shape = 0x0,350x0,350x350,0x350
; first_layer_temperature = 235
; first_layer_height = 0.250
; CONFIG_BLOCK_END


